/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SimpleGame;

import my.simplegame.MainMenu;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        MainMenu.main(args);
    }
}
